<?php
  
/**
 * Implements hook_field_info().
 *
 */
function jitsi_field_info() {
  return array(
    'jitsi' => array(
      'label' => t('Jitsi Meet'),
      'description' => t('This field allows you to insert a Jitsi Meet video conference into your content.'),
      'instance_settings' => array(
        'add_jitsi' => 0,
        'room_name' => '',
        'subject' => '',
      ),
      'default_widget' => 'jitsi_meet',
      'default_formatter' => 'jitsi_default',
    ),
  );
}

/**
 * Implements hook_field_validate().
 *
 */
function jitsi_field_validate($obj_type, $object, $field, $instance, $langcode, &$items, &$errors) {
  if ($field['type'] == 'jitsi') {
    // Validate functions here.
  }
}

function jitsi_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  $field = $form['#field'];
  
  if ($field['type'] == 'jitsi') {
    $form['field']['cardinality_container']['#disabled'] = TRUE;
    $form['field']['cardinality_container']['#description'] = t('We can insert a maximum of one Jitsi Meet conference currently.');
  }
}

/**
 * Implements hook_field_is_empty().
 *
 */
function jitsi_field_is_empty($item, $field) {
  if ($field['type'] == 'jitsi') {
    if (empty($item['add_jitsi'])) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implements hook_widget_info().
 *
 */
function jitsi_field_widget_info() {
  return array(
    'jitsi_meet' => array(
      'label' => t('Jitsi Meet'),
      'description' => t('Add a Jitsi Meet video conference.'),
      'field types' => array('jitsi'),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 *
 */
function jitsi_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $base = $element;
  $inputname = '';
  $prefix = '';
  $suffix = '';
  foreach ($form['#parents'] as $parent) {
    $inputname .= $prefix . $parent . $suffix;
    $prefix = '[';
    $suffix = ']';
  }
  $inputname .= '[' . $instance['field_name'] . '][' . $langcode . '][0][add_jitsi]';
  if ($instance['widget']['type'] == 'jitsi_meet') {
    $element['add_jitsi'] = array(
      '#type' => 'checkbox',
      '#title' => t('Add a Jitsi Meet video conference'),
      '#default_value' => !empty($element['#entity']->{$instance['field_name']}['und'][0]['add_jitsi']) ? $element['#entity']->{$instance['field_name']}['und'][0]['add_jitsi'] : 0,
    ) + $base;
    $element['subject'] = array(
      '#type' => 'textfield',
      '#title' => t('Subject'),
      '#description' => t('What is the subject of your meeting?'),
      '#default_value' => !empty($items[$delta]['subject']) ? $items[$delta]['subject'] : '',
      '#states' => array(
        'visible' => array(
          ':input[name="' . $inputname . '"]' => array('checked' => TRUE),
        ),
      ),
    ) + $base;
    // TODO: Make an advanced fieldset that is collapsed by default? So Room Name is hidden by default.
    $element['room_name'] = array(
      '#type' => 'textfield',
      '#title' => t('Room name'),
      '#description' => t('Leave blank for default. Using a simple room name increases the chance that someone you don\'t intend could guess the name or accidentally enter.'),
      '#element_validate' => array('jitsi_room_name_validate'),
      '#default_value' => !empty($items[$delta]['room_name']) ? $items[$delta]['room_name'] : openssl_encrypt('test'),
      '#states' => array(
        'visible' => array(
          ':input[name="' . $inputname . '"]' => array('checked' => TRUE),
        ),
      ),
    ) + $base;
  }
  return $element;
}

/**
 * Form element validation for Jitsi room name.
 */
function jitsi_room_name_validate($form, &$form_state) {
  if (empty($form_state['values'][$form['#parents'][0]]['und'][0]['room_name'])) {
    $site_name = config_get_translated('system.core', 'site_name');
    $key = settings_get('hash_salt');
    $form_state['values'][$form['#parents'][0]]['und'][0]['room_name'] = substr(backdrop_hmac_base64($site_name . $obj_type . $object->type . time(), $key), 0 , 32);
  }
}

/**
 * Implements hook_field_formatter_info().
 *
 */
function jitsi_field_formatter_info() {
  return array(
    'jitsi_default' => array(
      'label' => t('Embedded video'),
      'field types' => array('jitsi'),
    ),
    'jitsi_link' => array(
      'label' => t('Button linked to page'),
      'field types' => array('jitsi'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 */
function jitsi_field_formatter_view($obj_type, $object, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];
  $output = '';

  switch ($display['type']) {
    case 'jitsi_link':
      // Button linked to Jitsi Meet page.
      foreach ($items as $delta => $item) {
        if ($item['add_jitsi']) {
          $output = "TODO: Add jitsi link";
        }
        $element[$delta] = array('#markup' => $output);
      }
      break;
      
    case 'jitsi_default':
    default:
      foreach ($items as $delta => $item) {
        if ($item['add_jitsi']) {
          backdrop_add_js('https://meet.jit.si/external_api.js', array(
            'type' => 'external',
            'scope' => 'footer',
            'weight' => 10,
            )
          );
          $room_name = $object->{$instance['field_name']}['und'][0]['room_name'];
          $subject = $object->{$instance['field_name']}['und'][0]['subject'];
          $output = '<div id="meet"></div>';
          backdrop_add_js("
            const domain = 'meet.jit.si';
            const options = {
                roomName: '{$room_name}',
                width: '100%',
                height: 700,
                noSSL: false,
                configOverwrite: {
                  enableUserRolesBasedOnToken: true,
                  enableWelcomePage: false,
                  },
                interfaceConfigOverwrite: {
                  TOOLBAR_BUTTONS: [
                          'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
                          'fodeviceselection', 'hangup', 'profile', 'chat', 'recording',
                          'livestreaming', 'etherpad', 'sharedvideo', 'settings', 'raisehand',
                          'videoquality', 'filmstrip', 'invite', 'feedback', 'stats', 'shortcuts',
                          'tileview', 'videobackgroundblur', 'download', 'help', 'mute-everyone',
                          'e2ee'
                      ],
                  SHOW_PROMOTIONAL_CLOSE_PAGE: false,
                  DEFAULT_LOCAL_DISPLAY_NAME: 'self',
                  },
                parentNode: document.querySelector('#meet')
            };
            const api = new JitsiMeetExternalAPI(domain, options);
            api.executeCommand('password', 'securepassword!');
            api.executeCommand('subject', '{$subject}');
          ", array(
            'type' => 'inline',
            'scope' => 'footer',
            'weight' => 15,
            )
          );
        }
        $element[$delta] = array('#markup' => $output);
      }
      break;
  }

  return $element;
}
